# Site settings
title: Headerlabs
email: premcarver@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Prem is testing for desc
baseurl: "https://www.headerlabs.com" # the subpath of your site, e.g. /blog/
url: "https://www.headerlabs.com/new" # the base hostname & protocol for your site

# User setting
owner: Headerlabs
email: info@headerlabs.com
facebook_username: headerlab
twitter_username: headerlabs
github_username: headerlabs
address:
  - line: 1701 N. California Blvd. 
  - line: \#62 Walnut Creek, CA 94596
  # Feel free to add more lines here 
telephone: +1.510.393.2286
copyright: headerlabs.com

# API settings
google_api_key: keyof google

# Build settings
markdown: kramdown
